name: Publish SDK

on:
  push:
    tags:
      - "sdk-v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Use npm 11.20.0
        run: corepack enable && corepack prepare npm@11.20.0 --activate

      - name: Install
        run: npm install

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish --provenance --access public
